project:
  type: website

website:
  title: "Estimación bayesiana"
  navbar:
    pinned: true
    background: "#1F7349"
    right:
      - href: index.qmd
        text: Home



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

