project:
  type: website

website:
  title: "Estimación bayesiana"
  navbar:
    pinned: true
    background: "#F0DC14"
    right:
      - href: index.qmd
        text: Home
      - href: programa.qmd
        text: Programa



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

